### ISSUE TITLE
Created and CreatedAsMillisecondsEpocTime not set on Create<T>()

### ISSUE THREAD

**Issue by Jbower1** [anavarro9731/datastore#11]
When new Aggregates are created using `DataStoreCreateCapabilities.Create<T>()`, the `Created`, `CreatedAsMillisecondsEpochTime`, `Modified` and `ModifiedAsMillisecondsEpochTime` properties are set to `DateTime.MinValue`.

The issue here appears within `WalkGraphAndUpdateEntityMeta()`, it's checking to see if the properties are null & setting them to `DateTime.UtcNow` if they are null but since these properties are now non-nullable, they are being left at default (`DateTime.MinValue`):

```
else if (p.Name == nameof(IEntity.Created))
{
    //set created datetime if this is null
    if ((DateTime?)p.GetValue(current, null) == null)
    {
        p.SetValue(current, DateTime.UtcNow, null);
    }
}
else if (p.Name == nameof(IEntity.CreatedAsMillisecondsEpochTime))
{
    //set created datetime if this is null
    if (p.GetValue(current, null) == null)
    {
        p.SetValue(current, DateTime.UtcNow.ConvertToSecondsEpochTime(), null);
    }
}
```

**Comment by anavarro9731** [comment]
fixed in 6.2
