### ISSUE TITLE
HardDelete when using Version History

### ISSUE THREAD

**Issue by Crelo** [anavarro9731/datastore#13]
HardDelete throws an error when using Version History. HardDelete is failing if the aggregate does not exist and the Version History is activated.

Observation: TestDataCreator is deleting and recreating the aggregate with the same ID (Guid), this might create an issue if Version History already exists for that ID value.

**Comment by Crelo** [comment]
Error message from Seq:

CLRTYPE:System.Reflection.TargetException\r\nSystem.Reflection.TargetException: Non-static method requires a target.\r\n   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)\r\n   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)\r\n   at Raven.Client.Linq.LinqPathProvider.GetValueFromExpressionWithoutConversion(Expression expression, Object& value)\r\n   at Raven.Client.Linq.LinqPathProvider.GetValueFromExpression(Expression expression, Type type)\r\n   at Raven.Client.Linq.RavenQueryProviderProcessor`1.VisitEquals(BinaryExpression expression)\r\n   at Raven.Client.Linq.RavenQueryProviderProcessor`1.VisitAndAlso(BinaryExpression andAlso)\r\n   at Raven.Client.Linq.RavenQueryProviderProcessor`1.VisitQueryableMethodCall(MethodCallExpression expression)\r\n   at Raven.Client.Linq.RavenQueryProviderProcessor`1.VisitQueryableMethodCall(MethodCallExpression expression)\r\n   at Raven.Client.Linq.RavenQueryProviderProcessor`1.GetAsyncDocumentQueryFor(Expression expression)\r\n   at Raven.Client.Linq.RavenQueryProvider`1.ToAsyncDocumentQuery[TResult](Expression expression)\r\n   at Raven.Client.LinqExtensions.ToListAsync[T](IQueryable`1 source, CancellationToken token)\r\n   at TraceOne.ApiPlatform.DataStore.Impl.RavenDb.RavenDbRepository.<ExecuteQuery>d__6`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at DataStore.DataStoreQueryCapabilities.<ReadActive>d__8`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at DataStore.DataStore.<IncrementAggregateHistory>d__34`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at DataStore.DataStore.<DeleteHardById>d__28`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at TraceOne.Api.Audit.Logic.Operations.TemplateVersionOperations.<HardDelete>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at TraceOne.Api.Audit.Default.Msmq.Handlers.Commands.TemplateVersion.DeleteTemplateVersionHandler.<Handle>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at TraceOne.ApiPlatform.Infrastructure.MessageHandler`1.<HandleTyped>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at TraceOne.ApiPlatform.Infrastructure.MessageHandler`1.<HandleAny>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at TraceOne.ApiPlatform.Infrastructure.MessagePipeline.MessagePipeline.<Execute>d__13.MoveNext()

**Comment by anavarro9731** [comment]
Should be solved in latest release
