### ISSUE TITLE
DataStoreQueryCapabilities.Exists not using EventReplay events 

### ISSUE THREAD

**Issue by Jbower1** [anavarro9731/datastore#14]
When creating an aggregate with a specific id, and then calling `Exists()` prior to `CommitChanges()` will result in `false` being returned rather than `true`. This appears to be due to the previously executed events are not replayed.

Example:

```
testHarness.DataStore.Create(newCar).Wait();

\\ result should be true but comes across as false
var result = testHarness.DataStore.Exists(newCar.id).Result;
```

**Comment by anavarro9731** [comment]
exists has been removed, best way now is to use in (count > 0) which is supported without replay
