### ISSUE TITLE
DataStoreCreateCapabilities.Create<T> checks for exists already against model.id instead of newObject.id

### ISSUE THREAD

**Issue by Jbower1** [anavarro9731/datastore#15]
DataStoreCreateCapabilities.Create<T> has a guard against items that are already preexisting with the same id:

```
bool existsAlready = (await this.DsConnection.Exists(new AggregateQueriedByIdOperation(methodName, model.id)));
            Guard.Against(existsAlready, "An item with the same ID already exists", Guid.Parse("cfe3ebc2-4677-432b-9ded-0ef498b9f59d"));
```

However it's checking for `model.id` instead of `newObject.id`, this can cause issues if `model.id` is not yet set and the created aggregate id  is expected to be set by the call to `ForceProperties()` against `newObject`.

**Comment by anavarro9731** [comment]
fixed v6.2
